version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    env_file:
      - ./secrets/.env
    volumes:
      - ./app-data:/app/data
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: storage_db
    volumes:
      - db-data:/var/lib/postgresql/data
  stripe-listener:
    image: node:18
    working_dir: /listener
    volumes:
      - ./stripe-listener:/listener
    command: ["node", "listener.js"]
    env_file:
      - ./secrets/.env
volumes:
  db-data: {}
